### ISSUE TITLE
Colab notebook to label examples is not publicly accessible

### ISSUE THREAD

**Issue by BioGeek** [google-research/skai#279]
The [Colab notebook ](https://colab.research.google.com/drive/11RmU0h_-ehnsi2aSK7fl6P5__uwzBN_q?usp=sharing) to [label examples](https://github.com/google-research/skai/blob/0bd34f8773a63d6ee6a40867013246eeb9b4fda9/docs/assessment_instructions.md?plain=1#L221) is not publicly accessible.

**Comment by jzxu** [comment]
Thanks for pointing this out! That notebook was only a temporary solution until we had a proper labeling tool. We now have that so I'm removing the reference to that colab.
